### PR TITLE
assert newValues column name, closes #20

### LINKED ISSUE #20: Which checks should be done in `extractManualRecode`?
@beckerbenj :

Problem:  User can choose a column name for the new column in `useRecodeList()`. `extractManualRecode()` makes the assumption, the column with the recoded values is named `newValues`.
Should `extractManualRecode()` take an argument for the name of the new column or should `useRecodeList()` always force the column names `newValue`?

### PR DESCRIPTION
**Pull request by nickhaf**
removed `newCol` argument from `useRecodeList()`.
(sorry for the commit mess, commited to main by accident and reverted so i could get your feedback)

### CODE REVIEW

**Review by beckerbenj — CHANGES_REQUESTED** [review]
I just realized that I misremembered what the code/function does when answering to issue #20. Indeed, package wide we should assume (and verify) that all `recodeList` objects contain the two columns `oldValues` and `newValues`.
However, if `eatRecode` is used to recode a column in another `data.frame` it should be up to the user 
a) what column the user wants to recode (currently argument `oldCol`)
b) what the new column name with the recoded values should be called (currently argument `newCol`).

An example of this would be a user using recoding the variable TR_COUNTRY into TR_COUNTRY_r. 

Of course, `eatRecode` will be often used in combination with `eatGADS` and lookup tables. However, IMHO this connection should stay flexible.

My proposition would be two revert your proposed changes (sorry for not bringing this up sooner!) and rename the two arguments, e.g. into `varName` and `new_varName` two make it clear that those arguments do not refer to column names in the `recodeList`.

Also, again I am very sorry for not realizing this sooner and am open to other opinions :)

**Comment by nickhaf** [comment]
@beckerbenj : Just changed it, however i had the feeling it made the following workflow (extracting ManualRecodes, updating the data base) more cumbersome, as you always have to define the varName and new_varName arguments, so the functions now with which columns to work with. This in mind, I think it made more sense to define the column names in the beginning, so it's less for the user to think about.

**Comment by beckerbenj** [comment]
Ahh, I see, thanks for pointing that out! Should we discuss this via phone/zoom?

**Comment by nickhaf** [comment]
We talked about this and concluded that the function should stay as flexible as possible. This pull request can therefore be closed without merging, however we will have to deal with #20

**Pull request closed without merging**
