### PR TITLE
examples for `checkRecodeList` and `useRecodeList`

### PR DESCRIPTION
**Pull request by grewered**
I added examples for `checkRecodeList` and `useRecodeList`, I also updated the documentation, so that it's a bit more informative.

### CODE REVIEW

**Comment by grewered** [comment]
@nickhaf I changed the checks to checkmate-checks. Is that good like that or should I change it back?

**Comment by grewered** [comment]
ok, so some tests failed (they were fine for just the examples), but they are basically the same tests used in checkRecodeList. Could you look into it, why they failed? or maybe you could show me in march how I find that out myself (if it's not too difficult).

**Comment by nickhaf** [comment]
> @nickhaf I changed the checks to checkmate-checks. Is that good like that or should I change it back?

Yes that's great, thank you. Please adjust other tests as well in case you notice some.

**Comment by nickhaf** [comment]
> ok, so some tests failed (they were fine for just the examples), but they are basically the same tests used in checkRecodeList. Could you look into it, why they failed? or maybe you could show me in march how I find that out myself (if it's not too difficult).

There was a test for useRecodeList that also tested for the correct error message, which has changed because `checkmate` is used now. Updated it.

**Comment by nickhaf** [comment]
Looks great, I added some minor changes. Please link the according Issues in this pull-request and then merge, so the issues get closed automatically.

**Review by nickhaf — APPROVED** [review]

**Comment by apelalina** [comment]
closes #29 
closes #30

**Pull request merged**
