### PR TITLE
improve error message updateRecodeDB()

### LINKED ISSUE #39: Improve error messages
The `checkmate` assertions are not very informative for end users. 

Example: `updateRecodeDB()` throws an error, if columns in the database are not named correctly. However, the error message is not too easy to understand for end users. @grewered could you look into it, and let `checkmate` throw a clearer error message in that case, something like "please make sure the columns in your database are named `oldValues` and `newValues` (in each sheet if you have an excel file)" or something similar?

### PR DESCRIPTION
**Pull request by grewered**
current error message with assert_subset:

> Assertion on 'colnames(newRecodes)' failed: Must be a subset of {'oldValues','newValues'}, but has additional elements {'a','b'}

is that enough or should I look into customizing error messages?

### CODE REVIEW

**Review by nickhaf — CHANGES_REQUESTED** [review]
Yes the error message is fine, thanks! However, `assert_subset()` currently also throws an error if there is an additional column name, like `id` in the getting started vignette (That's why the checks are failing). Could you please rewrite it so it checks if `oldValues` and `newValues` is a subset of the column names (but there can be additional column names as well)? And sorry for the delay in reviewing.

**Comment by nickhaf** [comment]
Thanks for the change! However, I now found the error message to be a bit cryptic again: 
```
Fehler in updateRecodeDB(new_recodes1, directory = test_path(), newDirectory = d,  : 
  Assertion on 'c(oldValues, newValues)' failed: Must be a subset of {'oldValuess','newValues'}, but has additional elements {'oldValues'}.
``` 
I'd like something that points directly to the problem, like described here: https://forum.posit.co/t/implementation-best-practices-for-good-error-messages/4927

(Just because this kind of error message has already raised questions in users). @grewered do you have time to look into it/do you already know a good way to use checkmate to return custom error messages? Otherwise I can also try to find something.

**Comment by grewered** [comment]
I think you could use if (test_subset() == FALSE) { print("custom error message") } or something like that. 
test gives you TRUE/FALSE output. 
Other than that i don't think you can easily change the error message with checkmate, or at least I don't know how. 
or you could write a new function like here: 
https://mllg.github.io/checkmate/articles/checkmate.html#extending-checkmate

I could look at it next week, but I'm working on something else atm, so feel free to look for something.

**Comment by nickhaf** [comment]
closes #39

**Pull request merged**
